/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.datingapp;

import java.io.BufferedWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomi
 */
public class datingForm extends javax.swing.JFrame {

    
   
    private String name;
    private String eyeColour;
    private String hairColour;
    private String password;
    private int age;
    char[] passwordChar;
 
    private ArrayList<String> interests;
    List<JCheckBox> checkboxes;
    BufferedWriter output;
        
              
    /**
     * Creates new form datingForm
     */
    public datingForm() {
        initComponents();
        this.personalityListPanel.setVisible(false);
        interests = new ArrayList<>();
        checkboxes = new ArrayList<>();
        
        //adds all the checkboxes in the GUI to a list so that each selected item can be retrieved 
        //from the list.
        checkboxes.add(dancing);      
        checkboxes.add(writing);
        checkboxes.add(hiking);
        checkboxes.add(cooking);
        checkboxes.add(painting);
        checkboxes.add(gaming);
        checkboxes.add(football);
        checkboxes.add(photography);
        checkboxes.add(other);
       
        //hide initially unused panels
       this.otherEyeColourPanel.setVisible(false);
       this.otherHairColourPanel.setVisible(false);
       this.otherInterestsPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        eyeColourList = new javax.swing.JComboBox<>();
        hairColourList = new javax.swing.JComboBox<>();
        toggleInterestsList = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        otherEyeColourPanel = new javax.swing.JPanel();
        eyeColourOthers = new javax.swing.JTextField();
        personalityListPanel = new javax.swing.JPanel();
        dancing = new javax.swing.JCheckBox();
        writing = new javax.swing.JCheckBox();
        hiking = new javax.swing.JCheckBox();
        cooking = new javax.swing.JCheckBox();
        painting = new javax.swing.JCheckBox();
        football = new javax.swing.JCheckBox();
        photography = new javax.swing.JCheckBox();
        gaming = new javax.swing.JCheckBox();
        other = new javax.swing.JCheckBox();
        otherInterestsPanel = new javax.swing.JPanel();
        otherInterestsTextbox = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        otherHairColourPanel = new javax.swing.JPanel();
        hairColourOthers = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        loginText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Linker");
        setBackground(new java.awt.Color(255, 255, 255));

        nameText.setToolTipText("Username");

        eyeColourList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "brown", "blue", "hazel", "amber", "green", "grey", "red", "other" }));
        eyeColourList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeColourListActionPerformed(evt);
            }
        });

        hairColourList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "black", "brunette", "red", "blonde", "white", "other" }));
        hairColourList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColourListActionPerformed(evt);
            }
        });

        toggleInterestsList.setText("Toggle Interests List");
        toggleInterestsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleInterestsListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("Eye Colour");

        jLabel5.setText("Hair Colour");

        jLabel6.setText("Password");

        jLabel7.setText("Interests");

        otherEyeColourPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        otherEyeColourPanel.setMinimumSize(new java.awt.Dimension(7, 20));
        otherEyeColourPanel.setPreferredSize(new java.awt.Dimension(7, 20));

        javax.swing.GroupLayout otherEyeColourPanelLayout = new javax.swing.GroupLayout(otherEyeColourPanel);
        otherEyeColourPanel.setLayout(otherEyeColourPanelLayout);
        otherEyeColourPanelLayout.setHorizontalGroup(
            otherEyeColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eyeColourOthers, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        otherEyeColourPanelLayout.setVerticalGroup(
            otherEyeColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherEyeColourPanelLayout.createSequentialGroup()
                .addComponent(eyeColourOthers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dancing.setText("Dancing");

        writing.setText("Writing");

        hiking.setText("Hiking");

        cooking.setText("Cooking");

        painting.setText("Painting");

        football.setText("Football");

        photography.setText("Photography");

        gaming.setText("Gaming");

        other.setText("Other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otherInterestsPanelLayout = new javax.swing.GroupLayout(otherInterestsPanel);
        otherInterestsPanel.setLayout(otherInterestsPanelLayout);
        otherInterestsPanelLayout.setHorizontalGroup(
            otherInterestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherInterestsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(otherInterestsTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherInterestsPanelLayout.setVerticalGroup(
            otherInterestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherInterestsPanelLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(otherInterestsTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout personalityListPanelLayout = new javax.swing.GroupLayout(personalityListPanel);
        personalityListPanel.setLayout(personalityListPanelLayout);
        personalityListPanelLayout.setHorizontalGroup(
            personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalityListPanelLayout.createSequentialGroup()
                .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalityListPanelLayout.createSequentialGroup()
                        .addComponent(dancing)
                        .addGap(18, 18, 18)
                        .addComponent(painting)
                        .addGap(10, 10, 10)
                        .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(writing)
                            .addComponent(cooking))
                        .addGap(18, 18, 18)
                        .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(photography)
                            .addComponent(gaming)))
                    .addGroup(personalityListPanelLayout.createSequentialGroup()
                        .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hiking)
                            .addComponent(other, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(football)
                            .addComponent(otherInterestsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        personalityListPanelLayout.setVerticalGroup(
            personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalityListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dancing)
                    .addComponent(painting)
                    .addComponent(writing)
                    .addComponent(gaming))
                .addGap(18, 18, 18)
                .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiking)
                    .addComponent(football)
                    .addComponent(cooking)
                    .addComponent(photography))
                .addGap(18, 18, 18)
                .addGroup(personalityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(other, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otherInterestsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout otherHairColourPanelLayout = new javax.swing.GroupLayout(otherHairColourPanel);
        otherHairColourPanel.setLayout(otherHairColourPanelLayout);
        otherHairColourPanelLayout.setHorizontalGroup(
            otherHairColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherHairColourPanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(hairColourOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        otherHairColourPanelLayout.setVerticalGroup(
            otherHairColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hairColourOthers, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        registerButton.setBackground(new java.awt.Color(0, 51, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        loginText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginText.setText("Already registered? Login here");
        loginText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTextMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Milkshake", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Linker");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(otherEyeColourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eyeColourList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hairColourList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(otherHairColourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(passwordText)
                                        .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(toggleInterestsList))
                                    .addComponent(personalityListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(loginText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(hairColourList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherHairColourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(eyeColourList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))
                        .addComponent(otherEyeColourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleInterestsList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addComponent(personalityListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eyeColourListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeColourListActionPerformed
        // if the option 'other' is selected on the eye colour dropdown, a textbox is shown
        if(((String) this.eyeColourList.getSelectedItem()).equals("other")){
           
           this.otherEyeColourPanel.setVisible(true);
           
       }
        else{
       
       this.otherEyeColourPanel.setVisible(false);
     }
    }//GEN-LAST:event_eyeColourListActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        
        
        //Checks if the name text is empty and prompts the user to enter a name if it is
        if (this.nameText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter in your name" , "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
             setName(this.nameText.getText());  
        }
        
        //inserts the characters of the given password into a char array
        passwordChar = this.passwordText.getPassword();
        
        //prompts the user to change the password if the length is too short
        if(passwordChar.length <= 3){
            JOptionPane.showMessageDialog(this, "Password is too short" , "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            setPassword(new String(passwordChar));
        }
        
        
        
        //ensure that the right variable type is given with the try-catch method
        try{
            
            setAge(Integer.parseInt(this.ageText.getText())); 
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please set a valid age" , "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }       
        
        //Set the eye colour         
        //display an error message if nothing is selected
        if(this.eyeColourList.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please select an eye colour" , "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //display an input text field if none of the given options are viable
        else if(((String) this.eyeColourList.getSelectedItem()).equals("other")){
            
            //checks if the extra textbox is empty and prompts the user to enter it if it is
            if (this.eyeColourOthers.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter an eye colour " , "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                setEyeColour(this.eyeColourOthers.getText());
            }
        }
        
       //set the eye colour to selected value on dropdown menu
        else{
                setEyeColour((String) this.eyeColourList.getSelectedItem());
                }
        
        //Set hairColour 
        if(this.hairColourList.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please select a hair colour" , "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //display an input text field if none of the given options are viable
        else if(((String) this.hairColourList.getSelectedItem()).equals("other")){
            this.hairColourOthers.setVisible(true);
            if (this.hairColourOthers.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter a hair colour " , "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                setHairColour(this.hairColourOthers.getText());
            }
        }
        
       //set the hair colour to selected value on dropdown menu
        else{
                setHairColour((String) this.hairColourList.getSelectedItem());
                }
        
            //get the selected interest options and put them in an array
            for (JCheckBox checkbox : checkboxes) {
                if(checkbox.isSelected()){
                    if(!checkbox.getActionCommand().equals("Other")){
                        getInterests().add(checkbox.getActionCommand());
                    }
                    else{
                        if(!this.otherInterestsTextbox.getText().isBlank()){
                            getInterests().add(this.otherInterestsTextbox.getText());
                        }
                    }
                     
                }
            } 
            
        // instantiate an objet of the class registerUser which feed the user's data, given in the 
        //parameters, to a text file.
        try {
            registerUser registerUser = new registerUser(getName(), getPassword(), getEyeColour(), getHairColour(), getAge() , getInterests());
        } catch (IOException ex) {
            Logger.getLogger(datingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        //instantiates an object of 'userHome' which creates a user profile and passes the user information
        //so that it can be displayed
            userHome userhome = new userHome();
            
            userhome.setCurrentUser(getName(), getPassword(), getAge(), getHairColour(),
                                                        getEyeColour(), getInterests() );
            
            //opens the new GUI and closes the current one.
            userhome.setVisible(true);
            this.setVisible(false);
            
        
    }//GEN-LAST:event_registerButtonActionPerformed

    

    private void toggleInterestsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleInterestsListActionPerformed
        //show/hide the list of interest options for the user to chose from
        if (this.toggleInterestsList.isSelected()){
            this.personalityListPanel.setVisible(true);
        }
        else{
            this.personalityListPanel.setVisible(false);
        }
    }//GEN-LAST:event_toggleInterestsListActionPerformed

    private void loginTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTextMouseClicked
        //closes the 'register' GUI and opens the 'Login' GUI if the user is already registered.
        loginForm loginform = new loginForm();
        loginform.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginTextMouseClicked

    //does the same thing as 'eyeColourListPerformed' for the hairColour list
    private void hairColourListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColourListActionPerformed
     if(((String) this.hairColourList.getSelectedItem()).equals("other")){
           
           this.otherHairColourPanel.setVisible(true);
           
       }
     else{
       
       this.otherHairColourPanel.setVisible(false);
     }
    }//GEN-LAST:event_hairColourListActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
       
        if(other.isSelected()){
            this.otherInterestsPanel.setVisible(true);
        }
        else{
            this.otherInterestsPanel.setVisible(false);
        }
    }//GEN-LAST:event_otherActionPerformed

    
    //getters and setters
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the eyeColour
     */
    public String getEyeColour() {
        return eyeColour;
    }

    /**
     * @param eyeColour the eyeColour to set
     */
    public void setEyeColour(String eyeColour) {
        this.eyeColour = eyeColour;
    }

    /**
     * @return the hairColour
     */
    public String getHairColour() {
        return hairColour;
    }

    /**
     * @param hairColour the hairColour to set
     */
    public void setHairColour(String hairColour) {
        this.hairColour = hairColour;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the age
     */
    public int getAge() {
        return age;
    }

    /**
     * @param age the age to set
     */
    public void setAge(int age) {
        if (age < 16){
                JOptionPane.showMessageDialog(this, "You are too young to use this application" , "ERROR", JOptionPane.ERROR_MESSAGE);
               System.exit(0);
           }
           else{
              this.age = age;
           }
    }
     public ArrayList<String> getInterests() {
        return interests;
    }

    /**
     * @param interests the interests to set
     */
    public void setInterests(ArrayList<String> interests) {
        this.interests = interests;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cooking;
    private javax.swing.JCheckBox dancing;
    private javax.swing.JComboBox<String> eyeColourList;
    private javax.swing.JTextField eyeColourOthers;
    private javax.swing.JCheckBox football;
    private javax.swing.JCheckBox gaming;
    private javax.swing.JComboBox<String> hairColourList;
    private javax.swing.JTextField hairColourOthers;
    private javax.swing.JCheckBox hiking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginText;
    private javax.swing.JTextField nameText;
    private javax.swing.JCheckBox other;
    private javax.swing.JPanel otherEyeColourPanel;
    private javax.swing.JPanel otherHairColourPanel;
    private javax.swing.JPanel otherInterestsPanel;
    private javax.swing.JTextField otherInterestsTextbox;
    private javax.swing.JCheckBox painting;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JPanel personalityListPanel;
    private javax.swing.JCheckBox photography;
    private javax.swing.JButton registerButton;
    private javax.swing.JToggleButton toggleInterestsList;
    private javax.swing.JCheckBox writing;
    // End of variables declaration//GEN-END:variables
}

