/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.datingapp;

import java.util.ArrayList;

/**
 *
 * @author Tomi
 */
public class userHome extends javax.swing.JFrame {

   
    private String name;
    private String password;
    private int age;
    private ArrayList<String> interests;
    private String hairColour;
    private String eyeColour;
    
    private String priorityOne, priorityTwo, priorityThree, priorityFour, chosenGender;
    
    
    //create a method
    public void setCurrentUser(String name, String password, int age,  String hairColour, String eyeColour,ArrayList<String> interests) {
        this.name = name;
        this.password = password;
        this.age = age;       
        this.hairColour = hairColour;
        this.eyeColour = eyeColour;
        this.interests = interests;
        
        //display all the current user information on the GUI screen
        this.userName.setText(name);
        this.userAge.setText(", " + age);
        this.userHairColour.setText("Hair colour: " + hairColour);
        this.userEyeColour.setText("Eye Colour: " + eyeColour);
        this.userInterest.setText("Interests: " );
        
        for (String interest : interests) {
            
            userInterest.setText(userInterest.getText() + ", "+interest);
            
        }
    }
    /**
     * Creates new form userHome
     */
    public userHome() {
        initComponents();
        this.perferencesPanel.setVisible(false);
        this.chosenDatePanel.setVisible(false);
        
                
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        userProfilePanel = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        userAge = new javax.swing.JLabel();
        userHairColour = new javax.swing.JLabel();
        userEyeColour = new javax.swing.JLabel();
        userInterest = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        getDateButton = new javax.swing.JButton();
        perferencesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        priority1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        priority2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        priority3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        priority4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        preferenceOkButton = new javax.swing.JButton();
        chosenDatePanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        chosenDateName = new javax.swing.JLabel();
        chosenDateAge = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chosenDateInterests = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dateIdeaText = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userName.setText("Name");

        userAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userAge.setText(", Age");

        userHairColour.setText("Hair Colour: Sample Colour");

        userEyeColour.setText("Eye Colour: Sample Colour");

        userInterest.setText("Interests: Interest 1, Interest 2, Interest 3");

        javax.swing.GroupLayout userProfilePanelLayout = new javax.swing.GroupLayout(userProfilePanel);
        userProfilePanel.setLayout(userProfilePanelLayout);
        userProfilePanelLayout.setHorizontalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addComponent(userName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userAge))
                    .addComponent(userHairColour)
                    .addComponent(userEyeColour)
                    .addComponent(userInterest))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        userProfilePanelLayout.setVerticalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName)
                    .addComponent(userAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userHairColour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userEyeColour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userInterest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Profile");
        jLabel1.setAlignmentX(0.5F);

        getDateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getDateButton.setText("Get Date");
        getDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDateButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Preferences");

        jLabel8.setText("Please select your matching priorities according to their levels of priority");

        jLabel9.setText("1. ");

        priority1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Age range", "Hair Colour", "Eye Colour", "Interests" }));

        jLabel10.setText("2.");

        priority2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Age range", "Hair Colour", "Eye Colour", "Interests" }));

        jLabel11.setText("3.");

        priority3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Age range", "Hair Colour", "Eye Colour", "Interests" }));

        jLabel12.setText("4.");

        priority4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Age range", "Hair Colour", "Eye Colour", "Interests" }));

        jLabel13.setText("What gender would you like to date?");

        genderGroup.add(maleRadio);
        maleRadio.setText("male");

        genderGroup.add(femaleRadio);
        femaleRadio.setText("female");

        preferenceOkButton.setText("OK");
        preferenceOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenceOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout perferencesPanelLayout = new javax.swing.GroupLayout(perferencesPanel);
        perferencesPanel.setLayout(perferencesPanelLayout);
        perferencesPanelLayout.setHorizontalGroup(
            perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perferencesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(preferenceOkButton)
                    .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(perferencesPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(27, 27, 27)
                            .addComponent(maleRadio)
                            .addGap(18, 18, 18)
                            .addComponent(femaleRadio))
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addGroup(perferencesPanelLayout.createSequentialGroup()
                            .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(perferencesPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(priority1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10))
                                .addGroup(perferencesPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(priority3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12)))
                            .addGap(18, 18, 18)
                            .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(priority2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priority4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        perferencesPanelLayout.setVerticalGroup(
            perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perferencesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(priority1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(priority2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(priority3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(priority4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(perferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(maleRadio)
                    .addComponent(femaleRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preferenceOkButton))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Your Chosen Date");

        chosenDateName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chosenDateName.setText("NAME");

        chosenDateAge.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        chosenDateAge.setText(", Age");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Interests: ");

        chosenDateInterests.setText("Interest 1, Interest 2, Interest 3");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Your date Idea:");

        dateIdeaText.setText("Sample Date Idea");

        javax.swing.GroupLayout chosenDatePanelLayout = new javax.swing.GroupLayout(chosenDatePanel);
        chosenDatePanel.setLayout(chosenDatePanelLayout);
        chosenDatePanelLayout.setHorizontalGroup(
            chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chosenDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chosenDatePanelLayout.createSequentialGroup()
                        .addComponent(chosenDateName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chosenDateAge))
                    .addGroup(chosenDatePanelLayout.createSequentialGroup()
                        .addGroup(chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateIdeaText)
                            .addComponent(chosenDateInterests))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chosenDatePanelLayout.setVerticalGroup(
            chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chosenDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chosenDateName)
                    .addComponent(chosenDateAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(chosenDateInterests))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chosenDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(dateIdeaText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logOutButton.setText("Logout");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(getDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chosenDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(logOutButton)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOutButton)
                .addGap(30, 30, 30)
                .addComponent(userProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(getDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chosenDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDateButtonActionPerformed
        
        this.perferencesPanel.setVisible(true);
       
        
    }//GEN-LAST:event_getDateButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        
         loginForm loginform = new loginForm();
         loginform.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void preferenceOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenceOkButtonActionPerformed
       
        
        
         setPriorityOne((String) this.priority1.getSelectedItem());
         setPriorityTwo((String) this.priority2.getSelectedItem());
         setPriorityThree((String) this.priority3.getSelectedItem());
         setPriorityFour((String) this.priority4.getSelectedItem());
        
       
       
        if (this.maleRadio.isSelected()){
            setChosenGender("male");
            }
        else if(this.femaleRadio.isSelected()){
            setChosenGender("female");
        }
        else{
            setChosenGender("null");
        }
        
       
        //instantiate an object of 'matchalgorithms' to match the user with a suitable date and
        //pass the returned index to an integer.
        matchAlgorithms matchAlgorithms = new matchAlgorithms(this);
     
        
       int chosenDateIndex = matchAlgorithms.match();       
        this.chosenDatePanel.setVisible(true);
      
        //accesses the returned index from the female/males date class depending on user's choice, gets necessary
        //information and displays it on the user's screen.
        if (getChosenGender().equals("female")){
        
            femaledates date = new femaledates();
            this.chosenDateName.setText(date.names.get(chosenDateIndex));
            this.chosenDateAge.setText(", " + date.age.get(chosenDateIndex));
             this.chosenDateInterests.setText( " " );
             for (String interest : date.interests.get(chosenDateIndex)) {
                   
                 this.chosenDateInterests.setText(chosenDateInterests.getText() + ", " + interest);
                 
                 //acesses the method date idea in matchAlgorithm's class and displays the returned idea to the user
                 String dateIdea = matchAlgorithms.dateIdeas(interests, date.interests.get(chosenDateIndex));
             
                 this.dateIdeaText.setText(dateIdea);
            
        }
             
        }
       
        else if(getChosenGender().equals("male")){
        
        malesdates date = new malesdates();
            this.chosenDateName.setText(date.names.get(chosenDateIndex));
            this.chosenDateAge.setText(", " + date.age.get(chosenDateIndex));
             this.chosenDateInterests.setText( " " );
             for (String interest : date.interests.get(chosenDateIndex)) {
                  
                 this.chosenDateInterests.setText(chosenDateInterests.getText() + ", " + interest);
                 String dateIdea = matchAlgorithms.dateIdeas(interests, date.interests.get(chosenDateIndex));
             
                 this.dateIdeaText.setText(dateIdea);
             }
        }
    }//GEN-LAST:event_preferenceOkButtonActionPerformed
  /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the age
     */
    public int getAge() {
        return age;
    }

    /**
     * @param age the age to set
     */
    public void setAge(int age) {
        this.age = age;
    }

    /**
     * @return the interests
     */
    public ArrayList<String> getInterests() {
        return interests;
    }

    /**
     * @param interests the interests to set
     */
    public void setInterests(ArrayList<String> interests) {
        this.interests = interests;
    }

    /**
     * @return the hairColour
     */
    public String getHairColour() {
        return hairColour;
    }

    /**
     * @param hairColour the hairColour to set
     */
    public void setHairColour(String hairColour) {
        this.hairColour = hairColour;
    }

    /**
     * @return the eyeColour
     */
    public String getEyeColour() {
        return eyeColour;
    }

    /**
     * @param eyeColour the eyeColour to set
     */
    public void setEyeColour(String eyeColour) {
        this.eyeColour = eyeColour;
    }
    
     /**
     * @return the priorityOne
     */
    public String getPriorityOne() {
        return priorityOne;
    }

    /**
     * @param priorityOne the priorityOne to set
     */
    public void setPriorityOne(String priorityOne) {
        this.priorityOne = priorityOne;
    }

    /**
     * @return the priorityTwo
     */
    public String getPriorityTwo() {
        return priorityTwo;
    }

    /**
     * @param priorityTwo the priorityTwo to set
     */
    public void setPriorityTwo(String priorityTwo) {
        this.priorityTwo = priorityTwo;
    }

    /**
     * @return the priorityThree
     */
    public String getPriorityThree() {
        return priorityThree;
    }

    /**
     * @param priorityThree the priorityThree to set
     */
    public void setPriorityThree(String priorityThree) {
        this.priorityThree = priorityThree;
    }

    /**
     * @return the priorityFour
     */
    public String getPriorityFour() {
        return priorityFour;
    }

    /**
     * @param priorityFour the priorityFour to set
     */
    public void setPriorityFour(String priorityFour) {
        this.priorityFour = priorityFour;
    }

    /**
     * @return the chosenGender
     */
    public String getChosenGender() {
        return chosenGender;
    }

    /**
     * @param chosenGender the chosenGender to set
     */
    public void setChosenGender(String chosenGender) {
        this.chosenGender = chosenGender;
    }

           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chosenDateAge;
    private javax.swing.JLabel chosenDateInterests;
    private javax.swing.JLabel chosenDateName;
    private javax.swing.JPanel chosenDatePanel;
    private javax.swing.JLabel dateIdeaText;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JButton getDateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logOutButton;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JPanel perferencesPanel;
    private javax.swing.JButton preferenceOkButton;
    private javax.swing.JComboBox<String> priority1;
    private javax.swing.JComboBox<String> priority2;
    private javax.swing.JComboBox<String> priority3;
    private javax.swing.JComboBox<String> priority4;
    private javax.swing.JLabel userAge;
    private javax.swing.JLabel userEyeColour;
    private javax.swing.JLabel userHairColour;
    private javax.swing.JLabel userInterest;
    private javax.swing.JLabel userName;
    private javax.swing.JPanel userProfilePanel;
    // End of variables declaration//GEN-END:variables
}
